inherit_from: .rubocop_todo.yml

## rubocop 関連の gem を require します。
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-capybara
  - rubocop-factory_bot
  
  ## 全体に適応する項目を定義します。ここで Exclude に設定したファイルは、チェック対象外になります。
AllCops:
  TargetRubyVersion: 3.1
  TargetRailsVersion: 6.1
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'app/controllers/public/sessions_controller.rb'


